krampus:
   build:
    image: ghcr.io/nightwire/docker-krampus:main
    restart: always
    environment:
        - ts3maxgroupcount: 5
        - ts3address: teamspeak
        - ts3username: username
        - ts3password: password
   